spring:
  datasource:
    url: jdbc:mysql://${RDS_ENDPOINT:localhost}:3456/canary?sslMode=PREFERRED&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true&rewriteBatchedStatements=true&cachePrepStmts=true&prepStmtCacheSize=250&prepStmtCacheSqlLimit=2048&useServerPrepStmts=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${RDS_USERNAME:canary}
    password: ${RDS_PASSWORD:canary}
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      auto-commit: false

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: false
        show_sql: false
        order_inserts: true
        order_updates: true
        jdbc:
          batch_size: 1000
          fetch_size: 500
    open-in-view: false

logging:
  level:
    org.hibernate.SQL: off
    org.hibernate.type.descriptor.sql: off
    p6spy: OFF
    com.p6spy: OFF

mybatis:
  mapper-locations: classpath*:mybatis/mapper/**/*.xml
  type-aliases-package: com.spring.canary.category.domain
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    default-executor-type: SIMPLE # VALUES-foreach 다건 삽입이면 SIMPLE로도 충분히 빠름

decorator:
  datasource:
    enabled: false   # ✅ p6spy/datasource-proxy/flexy-pool 모두 비활성화